d_model: 62
d_state: 16
d_conv: 14
expand: 2
lr: 0.001
stride: 1
window_size: 32
prediction_distance: 1
name: mamba
data_dir: /mnt/BigHD_1/loucas/data-w-cubes/
batch_size: 32
num_workers: 0
data_portion: 0.4
episode_length: 200
