batch_size: 4
d_conv: 14
d_model: 80
d_state: 16
data_dir: /work/tc064/tc064/s2567498/data-w-camera/
data_portion: 1.0
episode_length: 200
expand: 2
lr: 0.001
name: mamba
num_workers: 0
prediction_distance: 1
resnet_features: 15
stride: 1
target_feature_indices:
- 2
- 4
window_size: 32
