batch_size: 32
d_model: 80
data_dir: /work/tc064/tc064/s2567498/data-w-camera/
data_portion: 1.0
dim_feedforward: 128
episode_length: 200
lr: 0.001
name: transformer
nhead: 20
num_decoder_layers: 3
num_encoder_layers: 3
num_workers: 0
prediction_distance: 1
resnet_features: 15
stride: 1
target_feature_indices:
- 7
window_size: 12
