batch_size: 8
d_model: 80
data_dir: /work/tc064/tc064/s2567498/data-w-camera/
data_portion: 1.0
dim_feedforward: 64
episode_length: 200
lr: 0.001
name: transformer
nhead: 10
num_decoder_layers: 2
num_encoder_layers: 2
num_workers: 0
prediction_distance: 4
resnet_checkpoint: /work/tc064/tc064/s2567498/resnet18-f37072fd.pth
resnet_features: 15
stride: 1
target_feature_indices:
- 7
- 8
- 9
window_size: 10
