batch_size: 16
d_conv: 20
d_model: 80
d_state: 24
data_dir: /work/tc064/tc064/s2567498/data-w-camera-reduced/
data_portion: 1.0
episode_length: 100
expand: 3
lr: 0.001
name: mamba
num_workers: 0
prediction_distance: 10
resnet_features: 15
stride: 1
target_feature_indices:
- 7
- 8
- 9
window_size: 20
