activation: tanh
batch_size: 8
d_model: 80
data_dir: /work/tc064/tc064/s2567498/data-w-camera
data_portion: 0.015
dim_feedforward: 128
end_lr: 0.001
episode_length: 200
limited_gpu_memory: true
name: transformer
nhead: 4
num_decoder_layers: 2
num_encoder_layers: 2
num_workers: 0
prediction_distance: 1
resnet_checkpoint: /work/tc064/tc064/s2567498/resnet18-f37072fd.pth
resnet_features: 15
start_lr: 0.005
stride: 1
target_feature_indices:
- 6
- 7
window_size: 10
